name: PIFu
channels:
- pytorch
- defaults
- conda-forge
- jmcmurray
- menpo
dependencies:
- opencv
- pytorch
- json
- openexr
- PIL
- scikit-image
- tqdm
- pyembree
- shapely
- rtree
- xxhash
- trimesh
#- PyOpenGL